Azure/communication-ui-library-ios

- eng/pipelines/jazzy-docs.yml
- eng/pipelines/jobs/CI-build-job.yml
- eng/pipelines/jobs/templates/build-and-coverage.yml
> [Bugfix] Update  pool version

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
* Podspec update
* Open...
* Click on...
> [Calling][Release] Podspec update

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
> [Release] Post Release Merge for AzureCommunicationUICalling 1.4.0-beta.1

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
> [Bugfix][Calling] On exit lost in merge

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/CallCompositeInternalError.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Setup/ErrorInfoViewModelTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
* Make no-network internal error propagate out
* updated internal error name, matched android behavior
> [Calling][Bug] Make no-network internal error propagate out (#689)

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Utilities/AccessibilityId.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
- AzureCommunicationUI/Podfile
- AzureCommunicationUI/Podfile.lock
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeCallState.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeDismissed.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/CallStateManager.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/CompositeExitManager.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/ACSCallingStateExtension.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Manager/CallStateManagerTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Manager/CompositeExitManagerTests.swift
> [Calling][Feature] CallStateChange and  Exit composite api arb feedback addressing

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Container/ContainerUIHostingController.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/LockPhoneOrientation.swift
> [Calling][Bug] If application is already in landscape mode CallComposite does not rotate properly

- AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
> [Calling][Bug] Orientation is applied only after trying to rotate a device

- AzureCommunicationUI/Podfile
- AzureCommunicationUI/Podfile.lock
* Upgrade Calling SDK to 2.6.0 to address M1 Simulator Support
* Open...
* Click on...
> Update calling SDK to 2.6.0

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
* Enable pip for UIKit part of demoapp
* Open...
* Click on...
> [Calling] Enable pip for UIKit part of demoapp

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
* Update calling changelog 1.4.0
* Open...
* Click on...
> [Calling] Update calling changelog 1.4.0

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Info.plist
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeOptions/DiagnosticConfigTests.swift
* Update version to 1.5.0-beta.1
* Open...
* Click on...
> [Calling] Update version to 1.5.0-beta.1

- AzureCommunicationUI/Podfile
- AzureCommunicationUI/Podfile.lock
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/README.md
* Use 2.6.0 Calling SDK
* Open...
* Click on...
> [Calling] Use 2.6.0 SDK

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
* Remove iphonesimulator exclusion.
* Open...
* Click on...
> [Calling] Remove iphonesimulator exclusion

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/ParticipantGridViewModel.swift
* Bug fix - hide disconnected participants - users who is was not admitted to the Teams meeting get disconnected status before be removed from the participant list. We should not show them.
* Open...
* Click on...
> [Calling] Bug fix - hide disconnected participants

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
* Demo all relaunch not working (fixing with async and delay to make sure composite exists before launching new)
> [Calling][DemoApp][Bug] relaunch composite not working

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/AudioSessionManager.swift
* change the audio is used logic to avoid the voiceover enable 
* Open...
* Click on...
> [Bug][Calling] Unable to join a call when VoiceOver is enabled

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/DemoInputTypes.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallConfiguration.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
Add one to N support 
Try to use 1:N calling in Swift UI 
* Open...
* Click on...
> Add 1 to N calling support

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
- AzureCommunicationUI/Podfile
- AzureCommunicationUI/Podfile.lock
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Info.plist
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeOptions/DiagnosticConfigTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/ViewModels/InfoHeaderViewModelMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/CallingViewModelTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/InfoHeaderViewModelTests.swift
* [Calling] Merge 1.5.0-beta-1 to 1.5.1-alpha.1
* Open...
* Click on...
> [Calling] Merge 1.5.0-beta-1 to 1.5.1-alpha.1

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Diagnostics/BottomToastDiagnosticView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Diagnostics/BottomToastDiagnosticViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Diagnostics/CallDiagnosticsViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Diagnostics/MessageBarDiagnosticView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Diagnostics/MessageBarDiagnosticViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/BottomToastDiagnosticViewModelTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/CallDiagnosticsViewModelTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/MessageBarDiagnosticViewModelTests.swift
Ensure that voice over announces message banner and bottom toast banners.
Ensure that icons don't participate in accessibility.
Fix accessibility label and hint localized key.
Fixed few typos.
Scenarios described on:
https://dev.azure.com/skype/SPOOL/_workitems/edit/3502660
https://dev.azure.com/skype/SPOOL/_workitems/edit/3502538
> [UFD] Fixes a few small issues related to accessibility on diagnostic banners

- AzureCommunicationUI/Podfile
- AzureCommunicationUI/Podfile.lock
- AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
- AzureCommunicationUI/sdk/AzureCommunicationUIChat/CHANGELOG.md
- AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Info.plist
- AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/ChatCompositeOptions/DiagnosticConfigTests.swift
* Update the ChatSDK to 1.3.3 for EUDB compliance
* Open...
* Click on...
> [Chat][Release] Update ChatSDK to 1.3.3 and release version bumping

- AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
- AzureCommunicationUI/sdk/AzureCommunicationUIChat/README.md
- scripts/main-repo-updater.py
* Final Release update
* 
* Open...
* Click on...
> [Chat][Release] Update the Readme for Chat 1.0.0-beta.4

- AzureCommunicationUI/Podfile
- AzureCommunicationUI/Podfile.lock
- AzureCommunicationUI/sdk/AzureCommunicationUIChat/AzureCommunicationUIChat.podspec
- AzureCommunicationUI/sdk/AzureCommunicationUIChat/CHANGELOG.md
- AzureCommunicationUI/sdk/AzureCommunicationUIChat/README.md
- AzureCommunicationUI/sdk/AzureCommunicationUIChat/Sources/Info.plist
- AzureCommunicationUI/sdk/AzureCommunicationUIChat/Tests/ChatCompositeOptions/DiagnosticConfigTests.swift
- scripts/main-repo-updater.py
* Back merge the release into develop branch
* Open...
* Click on...
> [Release] Back merge the release into develop branch

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeAvMode.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalOptions.swift
> API For Audio Only Mode

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeOptions.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/ViewModels/InfoHeaderViewModelMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/InfoHeaderViewModelTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Factories/CompositeViewModelFactoryTests.swift
* Fix PiP spelling to Pip
* Open...
* Click on...
> [Calling][Bugfix] Pip fix spelling

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
* Fix double Leave Confirmation drawer appearance.
* Open...
* Click on...
> [Calling] Fix double Leave Confirmation drawer appearance

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppAudioOnlyTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalOptions.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/ViewModels/ControlBarViewModelMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/ViewModels/SetupControlBarViewModelMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/ControlBarViewModelTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Setup/SetupControlBarViewModelTests.swift
* Update avMode naming univerally.
* Open...
* Click on...
> change avMode to audioVideoMode universally

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Utilities/LandscapeAwareKeyboardWatcher.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/SupportForm/SupportFormView.swift
> [Calling][Bugfix] Fix support form in Landscape mode + Keyboard support

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Utilities/LandscapeAwareKeyboardWatcher.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/SupportForm/SupportFormView.swift
* Updates to the keyboard height/orientation detection
* Open...
* Click on...
> [Calling][Bugfix] Keyboard height detection not working in certain scenarioes.

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewModel.swift
> [Bugfix][Calling] PiP was showing support form

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-GB.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-US.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
* Fix a typo in the En Admit all
* Open...
* Click on...
> [Calling][Bugfix] Admit all typo

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeParticipantsList.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/ParticipantsListViewController.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListViewModel.swift
* Apply localization to Admit All button
* Open...
* Click on...
> [Calling][Bugfix] Apply localization to Admit All button

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-GB.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-US.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
* Camera accessibility is not same as Video off/on, Mic Off/On 
* Open...
* Click on...
> [Calling][Bug] Visual label and accessible name are not similar for control. 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeCallKitOptions.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeCallKitRemoteInfo.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeCallState.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeCallerInfo.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeIncomingCallCancelledInfo.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeIncomingCallInfo.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeOptions.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositePushNotificationEventType.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositePushNotificationInfo.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallScreenControlBarOptions.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallScreenOptions.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
* public api for 1 to 1 calling
* public api for disable leave confirm dialog
> [Calling] public API for 1.7.0 beta.1

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
Resolve Ticket #3508029
Error when joining a teams meeting with whitespace in the link
* Open...
* Click on...
> [Calling][Bugfix] Whitespace trimming for Teams Meeting Links

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeLeaveCallConfirmation.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallScreenControlBarOptions.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LeaveCallConfirmationOptions.swift
> [Calling] fix API feedback 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/VideoView/LocalVideoView.swift
* ignore camera smart invert to match the behaviour with local camera.  
* Open...
* Click on...
> [Calling][Bug] Camera smart invert

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarView.swift
> [Calling][Bug] Update Focus for audio device button  

- AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
* Update the support version to 15 (n-2)
* Open...
* Click on...
> [Calling][Refactor] Update the support version 

- AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
* Update the support version to n-2. 
* Open...
* Click on...
> [Calling][Refactor] Update the support version  (#844)

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/README.md
- eng/jazzy/AzureCommunicationUICalling.yml
* Update library version to 1.16.1
* Update the min support version to 15
* Open...
* Click on...
> [Calling][Release]Update the release version

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallScreenControlBarOptions.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LeaveCallConfirmationMode.swift
* Use mode instead of options
* Use object name instead of for
* Open...
* Click on...
> [Calling][Refactor] modify public API following feedback

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/UITestCallingSDKWrapper.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/FloatingUITestWindow.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
* CallComposite isHide should work through action dispatch
* Open...
* Click on...
> [Calling][Bugfix] CallComposite isHide

- azure-pipelines.yml
- eng/pipelines/release.yml
* Update pipeline with FederatedIdentity 
* Update touchdown service version 
* Update release pipeline using key valut 
* Open...
* Click on...
> [Refactor] Update Localization and release pipeline pipeline 

- AzureCommunicationUI/Podfile
- AzureCommunicationUI/Podfile.lock
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/README.md
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Info.plist
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeOptions/DiagnosticConfigTests.swift
- eng/jazzy/AzureCommunicationUICalling.yml
* disable leave call confirmation
* short meeting URL support
> [Calling][Release] Update versions for 1.7.0

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/DemoInputTypes.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/UITestCallingSDKWrapper.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallConfiguration.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LocalOptions.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/ParticipantRole.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/RemoteOptions.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingSDKWrapperProtocol.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeOptions/RemoteOptionsTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/CallingSDKWrapperMocking.swift
> [Calling][Feature] disable rooms for 1.7.0 GA

- AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/UITestCallingSDKWrapper.swift
- AzureCommunicationUI/Podfile
- AzureCommunicationUI/Podfile.lock
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Model/CapabilitiesChangedEvent.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Model/CapabilitiesChangedReason.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Model/CapabilityResolutionReason.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Model/ParticipantCapability.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Model/ParticipantCapabilityType.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKEventsHandler.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingSDKWrapperProtocol.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingService.swift
* The changes include service layer implementation to get capabilities and capabilities change events
* The underlaying headless sdk used is a private drop compiled from the latest master on May 26th.
* Open...
* Click on...
> Initial Service implementation for Capability Change events

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/DemoInputTypes.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
* Add the logic to check the group call id is valid or not 
* if it is not valid, show the error and cannot join the call 
* Open...
* Click on...
> [Call][Bug] Add Logic to check the group call ID 

- azure-pipelines.yml
* Based on the requirement, updated to latest version
* Open...
* Click on...
> [Calling][Refactor] Update touchdown task version

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewFactory.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/CaptionsViewManager.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsInfoView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsListView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsTableViewController.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKEventsHandler.swift
* ...
- [ x] No
- [x ] Feature
- [] Color Theming
- [] iOS supported versions (all major versions greater than or equal current target deployment version)
Open the app, tap Call - Swift UI
Fill in call tokens and ids
Start the call
see the captions poping up on the bottom
> Add UIKit caption table view. Add caption simulation

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
* Expose cx provider for beta only
> [Calling][Feature] cx provider support from native sdk

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ar-SA.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/de-DE.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/es-ES.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fi-FI.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fr-FR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/he-IL.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/it-IT.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ja-JP.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ko-KR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nb-NO.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nl-NL.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pl-PL.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pt-BR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ru-RU.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/sv-SE.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/tr-TR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hans-CN.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hant-TW.lproj/Localizable.strings
* Update the string 
* Open...
* Click on...
> [Calling] Update the String 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/CaptionsViewManager.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsTableViewController.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKEventsHandler.swift
> Connect real caption subject

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
* On dismiss exit event is not called
* crash on get log file
> [Calling][BugFix] crash on get log file and exit event not called

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
* notify composite dismiss only once
> [Calling][BugFix] notify composite dismiss only once

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
> [Calling][BugFix] remove duplicate code

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
* Fix dismiss event is called multiple time
* Open...
* Click on...
> [Calling][BugFix][MergeConflict] Dismiss event is fired multiple time

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/ParticipantsListViewController.swift
* Fix didSelect for the plus more menu item
* Open...
* Click on...
> [Calling][BugFix] Fix didSelect for the plus more menu item

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsInfoView.swift
* Update the scroll logic
* Open...
* Click on...
> [Calling][Bug] Update the scroll logic 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsInfoView.swift
* Fix isLastItemVisible logic
* Open...
* Click on...
> [Calling][Bug] Fix captions scroll issue 

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsInfoView.swift
* After captions is over 50, the index logic is broken 
* Add copy for the alert to get the call id 
* Open...
* Click on...
> [Calling][Bug] Update the scroll issue for captions over limit

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsInfoCellView.swift
* Wrap captions text to the next line instead of being truncated
* Open...
* Click on...
> [Calling][Refactor] Wrap captions text to the next line instead of being truncated

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/README.md
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Info.plist
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeOptions/DiagnosticConfigTests.swift
- eng/jazzy/AzureCommunicationUICalling.yml
* Update the changelog and release version 
* Open...
* Click on...
> [Calling][Release] Update the change log 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallDurationTimer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/CallDurationManager.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
Task 3825794 iOS :
-> Added VoiceOver in Timer
-> Added a format for timer
* ...
* Open...
* Click on...
> Task  3825794[SDE] UI control and UX workflow works in VoiceOver (iOS)

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/CallDurationManager.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Manager/CallDurationManagerTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/ViewModels/InfoHeaderViewModelMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/InfoHeaderViewModelTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Factories/CompositeViewModelFactoryTests.swift
* Call Duration Timer Tests Implementation
* Open...
* Click on...
> Call Duration Timer Tests Implementation

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/CallDurationManager.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
> Timer API Bug Bash 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Style/ColorThemeProvider.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsInfoCellView.swift
* Change the colour based on the updated design
* Open...
* Click on...
> [Calling][Bug] Update the captions color 

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
* Fix the demo app with release pipeline 
* Refactor the form to be List 
* Open...
* Click on...
> [Bug][Calling] Fix the demo app 

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
* Setting page implementation for title subtitle feature test
* Open...
* Click on...
> Setting page implementation for title subtitle feature test

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
* Fix the demo app 
* Open...
* Click on...
> [Calling][Bug] Fix demo app for release pipeline 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
* Accessibility fix for talkback on custom title & subtitle for dynamic update
* Open...
* Click on...
> Accessibility fix for talkback on custom title & subtitle for dynamic update

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
* Demo App CallScreenOptions creation updated
* Open...
* Click on...
> [Calling][Task] Demo App CallScreenOptions creation updated

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsInfoCellView.swift
* Fix the voiceover cannot announce different languages 
* Open...
* Click on...
> [Calling][Bug] Update the captions text for different languages 

- AzureCommunicationUI/Podfile
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/README.md
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Info.plist
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeOptions/DiagnosticConfigTests.swift
* 1.11.0 beta.2 merge to develop
* Open...
* Click on...
> [Calling][Release] 1.11.0 beta.2 merge to develop

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Button/PrimaryButton.swift
* Fix button click Xcode15
* Open...
* Click on...
> [Calling][Bugfix] Fix button click Xcode15

- eng/jazzy/AzureCommunicationUICalling.yml
* Update jazzy doc version
* Open...
* Click on...
> [Caling] Update jazzy doc version

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallScreenHeaderViewData.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallScreenOptions.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactoryProtocols.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/RemoteParticipantsManager.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/UpdatableOptionsManager.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Action/Action.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Action/CallScreenInfoHeaderAction.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/AppStateReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/CallDiagnosticsReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/CallScreenInfoHeaderReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/CallingReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/ErrorReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/NavigationReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/AppState.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/CallScreenInfoHeaderState.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/ViewModels/InfoHeaderViewModelMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/CallDiagnosticsViewModelTests.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/InfoHeaderViewModelTests.swift
* Remove the feature flag
* Open...
* Click on...
> [Calling][Refactor] Remove the feature flag for custom title

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/CallingViewModelTests.swift
* Fix UI update on exit from PiP
* Open...
* Click on...
> [Calling][Bugfix] iOS 18 PiP exit

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/AppLifeCycleManager.swift
* iOS18 changed NotificationCenter internal logic, as a result when go back and force to PiP, UI Library ends up in incorrect lifecycle state.
* Open...
* Click on...
> [Calling][Bugfix] iOS18 camera off

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/Views/DrawerBodyTextView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/Views/DrawerSelectableItemView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/LeaveCallConfirmation/LeaveCallConfirmationViewModel.swift
* Update the button drawer cell accessibility role for button 
* Open...
* Click on...
> [Calling][Bug] Update the button role for accessibility

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
* Add pip feature in the changelog
* Open...
* Click on...
> [Calling][Release] Update the changelog 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Captions/CaptionsInfoView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/CustomAlert/CustomAlert.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/BottomDrawer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/Views/DrawerTitleView.swift
* Update the color based on design 
* Open...
* Click on...
> [Calling][Bug] Update colour for accessibility

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/Views/DrawerBodyTextView.swift
* Update the drawer color 
* Open...
* Click on...
> [Calling][Bugfix] Update the drawer color

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
- eng/jazzy/AzureCommunicationUICalling.yml
* Update the pod spec version 
* Open...
* Click on...
> [Calling][Release] Update the podspec 

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift
* when it is simulator, disable the callkit by default 
* Open...
* Click on...
> [Calling][Refactor] Refactor callkit default value for simulator 

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/UITestCallingSDKWrapper.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallScreenHeaderViewData.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactoryProtocols.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/UpdatableOptionsManager.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Action/ButtonViewDataAction.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Action/CallingAction.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/ButtonViewDataReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/CallingReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/ErrorReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/NavigationReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/ButtonViewDataState.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/CallingState.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKEventsHandler.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingSDKWrapperProtocol.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingService.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallingSDKEventsHandlerMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/CallingSDKWrapperMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/CallingServiceMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/ViewModels/InfoHeaderViewModelMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/InfoHeaderViewModelTests.swift
* remove feature flag for start timer 
* enable the beta feature 
* Open...
* Click on...
> [Calling][Refactor] Clean up the GA feature flag and enable beta feature 

- AzureCommunicationUI/AzureCommunicationUIDemoApp/AzureCommunicationUIDemoApp.xcodeproj/project.pbxproj
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj
- eng/pipelines/ci.yml
- eng/pipelines/release.yml
* Update the pool
* Update the ESRP 
* Change 1ESPT template 
* Update iOS target version 
* Open...
* Click on...
> [Calling][Refactor] Update release pipeline 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellView.swift
* Remove the opacity based on the design
* Update the focus after the hold state changed
* Open...
* Click on...
> [Calling][Bug] Fix the focus and colour based on design 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
* Dispose SDK initializer along with SDK wrapper
* Open...
* Click on...
> [Calling][Bugfix] Dispose sdk initializer

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Banner/BannerTextView.swift
* Adjust the max and min text size
* Open...
* Click on...
> [Calling][Bugfix] Add the max and mini text size 

- azure-pipelines.yml
* Update pipeline template 
* Open...
* Click on...
> [Calling][Refactor] Refactor pipeline - localization

- AzureCommunicationUI/Podfile
- AzureCommunicationUI/Podfile.lock
> Update Chat Dependency from 1.3.3 to 1.3.6

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift
* Update the control bar logic
* Open...
* Click on...
> [Calling][Bug] Update control bar logic when user is in lobby 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Container/ContainerUIHostingController.swift
* Enable the orientation notification as we support more orientation 
* Open...
* Click on...
> [Calling][Bug] Enable the orientation notification 

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewModel.swift
* Fix demo app spelling 
* Fix the start experience for PIP mode
* Fix the crash for back button 
* Open...
* Click on...
> [Calling][Bug] Fix demo app spelling, setup and crash 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Info.plist
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeOptions/DiagnosticConfigTests.swift
* Update the version to 1.14.0-beta.2
* Open...
* Click on...
> [Calling][Release] Update the version and changelog

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ar-SA.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/de-DE.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-GB.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/es-ES.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fi-FI.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fr-FR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/he-IL.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/it-IT.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ja-JP.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ko-KR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nb-NO.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nl-NL.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pl-PL.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pt-BR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ru-RU.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/sv-SE.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/tr-TR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hans-CN.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hant-TW.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/ParticipantActions/ParticipantMenuViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift
* Update the missing string 
* Open...
* Click on...
> [Calling][Bug] Update the missing string 

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/ParticipantGridView.swift
* Remove the extra padding for participant view
* Open...
* Click on...
> [Calling][Bug] Remove the extra padding for participant view

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/CaptionsRttDataManager.swift
* Remove the extra captions text when transcription is on 
* Open...
* Click on...
> [Calling][Bug] Remove the extra captions text 

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/UITestCallingSDKWrapper.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Action/CallingAction.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/CallingReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/ErrorReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/NavigationReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/CallingState.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKEventsHandler.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingSDKWrapperProtocol.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingService.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallingSDKEventsHandlerMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/CallingSDKWrapperMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/CallingServiceMocking.swift
* Disable beta feature
* Open...
* Click on...
> [Calling][Refactor] Disable Beta feature

- AzureCommunicationUI/Podfile
- AzureCommunicationUI/Podfile.lock
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.podspec
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Info.plist
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallCompositeOptions/DiagnosticConfigTests.swift
* Bring release to main branch
* Open...
* Click on...
> [Release] Merge AzureCommunicationUICalling 1.14.1

- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Mockings/UITestCallingSDKWrapper.swift
- AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Action/CallingAction.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/CallingReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/ErrorReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Reducer/NavigationReducer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/State/CallingState.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKEventsHandler.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingSDKWrapperProtocol.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/CallingService.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CallingSDKEventsHandlerMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/CallingSDKWrapperMocking.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/CallingServiceMocking.swift
* Disable the beta feature
* Open...
* Click on...
> [Calling][Release] Disable the beta feature

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Style/ColorThemeProvider.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/CaptionsRtt/CaptionsRttInfoCellView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/Views/CustomTextField.swift
* Update the text and background color
* Open...
* Click on...
> [Calling][Bug] Update the text and background color

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ar-SA.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/de-DE.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-GB.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/es-ES.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fi-FI.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fr-FR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/he-IL.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/it-IT.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ja-JP.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ko-KR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nb-NO.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nl-NL.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pl-PL.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pt-BR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ru-RU.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/sv-SE.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/tr-TR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hans-CN.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hant-TW.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactoryProtocols.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/CaptionsRtt/CaptionsRttListViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/DrawerViewModels.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/Views/DrawerGenericItemView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift
* Caption language and spoken language disable state
* Open...
* Click on...
> [Calling][Bug] Update accessibility disable state

- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ar-SA.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/de-DE.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-GB.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/es-ES.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fi-FI.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/fr-FR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/he-IL.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/it-IT.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ja-JP.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ko-KR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nb-NO.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/nl-NL.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pl-PL.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/pt-BR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/ru-RU.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/sv-SE.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/tr-TR.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hans-CN.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/zh-Hant-TW.lproj/Localizable.strings
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/CaptionsRtt/CaptionsRttInfoCellView.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/CaptionsRtt/CaptionsRttListViewModel.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/BottomDrawer.swift
- AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift
* Refactor the dismiss overlay accessibility 
* Add back button accessibility label 
* Open...
* Click on...
> [Calling][Bug] Dismiss overlay accessibility and back button
