AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupView.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewComponent/PreviewAreaView.swift
* Fixes the UI overlap bug on permission view in setup screen
* Open...
* Click on...
| 
| 
|
=> [BugFix][Calling] Permission view settings button overlap UI bug fixed

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Error/ErrorInfoViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/CallCompositeInternalError.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Setup/ErrorInfoViewModelTests.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
* On setup screen, when network error is detected, it is an internel "connectFailed" event that did not have a mapping. I added a mapping to the public noNetworkConnection error.
* Open...
* Click on...
=> [Calling][Bug] Make no-network internal error propagate out

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift
* Change the button type into InfoButton
* Open...
* Click on...
|![IMG_0034](https://github.com/Azure/communication-ui-library-ios/assets/93549644/7716086b-e2b9-451c-8990-dca118795f52)|![IMG_0036](https://github.com/Azure/communication-ui-library-ios/assets/93549644/94afaeda-64ae-4d11-a4d9-1f76d64cf948)|
=> [Bug][Calling] Back button colour on InfoHeader 

AzureCommunicationUI/Podfile, AzureCommunicationUI/Podfile.lock, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
* Making code changes as per latest SDK to fix issue where only on iOS 15 we need to set default video type to not raw (works fine on iOS 16)
* With fix iOS 15 will see remote participant video
=> [Calling][Bug] iOS15 remote participant video event not received

AzureCommunicationUI/sdk/AzureCommunicationUICalling/CHANGELOG.md, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ParticipantsListViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/ParticipantGridViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Builder/ParticipantInfoModelBuilder.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/InfoHeaderViewModelTests.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/ParticipantGridsViewModelTests.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/ParticipantsListViewModelTests.swift
* Filter our InLobby and Disconnected users from UI. We should not display users in the grid nor in participant list until they are admitted to the Team meeting call. Also, when user is rejected, we first receive Disconnected status followed by Participant list updated event when participant is removed. The time gap is about 1 sec. To avoid user be displayed for a second, also filter out Disconnected.
* Open...
* Click on...
=> [Calling] Filter our InLobby and Disconnected users from UI

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Service/Calling/AzureCommunicationCalling/CallingSDKWrapper.swift
* Start a call with video ON fix
* Launch CallComposite
* turn camera ON in the Setup screen
* Join a call
| Observe that on the remote device another participant can see our outgoing video | Screenshot or description with this change | Before it did not go out and remote user did not see vidoe.
=> [Calling][Bugfix] Start a call with video ON fix

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Diagnostics/BottomToastDiagnosticView.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Diagnostics/BottomToastDiagnosticViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Diagnostics/CallDiagnosticsViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Diagnostics/MessageBarDiagnosticView.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Diagnostics/MessageBarDiagnosticViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/BottomToastDiagnosticViewModelTests.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/CallDiagnosticsViewModelTests.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/MessageBarDiagnosticViewModelTests.swift
Ensure that voice over announces message banner and bottom toast banners.
Ensure that icons don't participate in accessibility.
Fix accessibility label and hint localized key.
Fixed few typos.
Cherry-pick of https://github.com/Azure/communication-ui-library-ios/pull/769
Scenarios described on:
https://dev.azure.com/skype/SPOOL/_workitems/edit/3502660
https://dev.azure.com/skype/SPOOL/_workitems/edit/3502538
=> [UFD][1.5.0] Fixes a few small issues related to accessibility on diagnostic banners

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Utilities/LandscapeAwareKeyboardWatcher.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/SupportForm/SupportFormView.swift
Fix the keyboard handler. Was in the View and recreation was setting the offset to 0, causing the form to jump back down.
Migrated to singleton which works reliably (no recreation, no resetting to 0, no jumping).
Weighed singleton decision against alternatives (DI, Redux) but this seems like safest/lowest impact approach for the moment.
DI: Would require changes to the interface of the watcher, as well as propagating to VM's (estimated +20-50 lines, +3 files at least)
Redux: Would require changes to the interface to be more of a "manager" + redux state + propagating to VM's. (estimated +40-80 lines, +5-10 files changed)
vs
Singleton: One global keyboard, everyone can use the same instance in their view, quick and easy. Very little tracked in static state. (2 files changed, +2 lines).
* …
=> [Calling][Bugfix] Keyboard watcher state was resetting with Views/Viewmodels

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/InfoHeaderView.swift
=> [Calling][Bug]Text 'Call with 1 person' is truncated after applying large text size on 'Calling screen'.

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-GB.lproj/Localizable.strings, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en-US.lproj/Localizable.strings, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/OnHoldOverlayViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift
* Proper Name should be defined for 'Resume' button. Voiceover should announce something like 'Resume' button.
* Open...
* Click on...
=> [Calling][Bug] Update resume button label

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/LeaveCallConfirmationListViewController.swift
* 'Leave call' heading should be adopting a larger text setting. Text size should be increased according to resize settings.
* Open...
* Click on...
|<img width="1272" alt="Textual information like 'Leave call' heading does not adopt larger text settings" src="https://github.com/Azure/communication-ui-library-ios/assets/93549644/fab99498-1411-49ae-9155-079b09fe913e">|![IMG_7943](https://github.com/Azure/communication-ui-library-ios/asse …
=> [Calling][Bug] Leave call button accessibility

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarView.swift
* Keyboard focus does not return to 'Speaker button' after closing the popup of speaker on 'Set up' screen. Keyboard focus returns to back control.
* Open...
* Click on...
=> [Calling][Bug] Audio device button focus

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/AppLifeCycleManager.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Redux/Middleware/CallingMiddlewareHandler.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Redux/Middleware/CallingMiddlewareHandlerTests.swift
* Switch camera off when user opens AppCenter or user locks screen
* Open...
* Click on...
=> [Calling][iOS][Bugfix] Switch camera off when user opens AppCenter or user Locks screen

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift
* Voiceover doesn't announce any information regarding 'Video is On/Off' for participants who have joined the call. It announces 'Username, Muted/Unmuted' information only.
* Open...
* Click on...
=>  [Calling][Bug] Fix VoiceOver announcements for remote camera state changes.

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings
* we want to setup the label same as the current button. 
* 
* Open...
* Click on...
=> [Calling][Bug]Mic on/off button accessibility

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupView.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Setup/SetupViewComponent/SetupControlBarView.swift
* Focus won't be back to device button because of the complex layout 
* Add the accessibilityElement(children: .contain) to let voiceover get the children layout element 
* Set the order to HStack, which will help to be back to deviceButton
* Open...
* Click on...
=> [Calling][Bug] Update focus after device select list dismiss

AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift, AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Utilities/AccessibilityId.swift, AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift, AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoViewController.swift, AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/SettingsView.swift, AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/AzureCommunicationUIDemoAppE2ETests.swift, AzureCommunicationUI/AzureCommunicationUIDemoApp/Tests/Utilities/XCUITestBase.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/AzureCommunicationUICalling.xcodeproj/project.pbxproj, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallComposite.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallCompositeOptions.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallScreenControlBarOptions.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/CallScreenOptions.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/CallCompositeOptions/LeaveCallConfirmationMode.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactory.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Factories/CompositeViewModelFactoryProtocols.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/ControlBarViewModelExtension.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/CompositeViewModelFactoryMocking.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Mocking/ViewModels/ControlBarViewModelMocking.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/CallingViewModelTests.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Calling/ControlBarViewModelTests.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Tests/Presentation/Factories/CompositeViewModelFactoryTests.swift
This feature introduce an option into CallCompositeBuilder to enable/disable the "Leave Call?" confirmation dialog. If disable, the "End Call" button will directly end the call without prompt.
* Open...
* Click on...
=> [Calling][Feature] Leave call confirmation mode

AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/EnvConfig.swift, AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Info.plist, AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift, AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/EntryViewController.swift
* In development, time can be drained getting to the setup/call screen. This introduces "jumpTo" for EnvConfig.xcconfig, it can be set to "MockCallScreen", "MockSetupScreen" and will get into the composite faster if setup locally.
* Debug builds only
* Open...
* Click on...
=> Support for "Quick jumping" into the Mocked Composite

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/Manager/AudioSessionManager.swift
* State gets stuck in "requesting" mode, which prevents the VM from populating the list. Dispatch additional action on error for "audioDeviceChangeSucceeded", with the currently detected device, to set the state back into the proper mode.
* Open...
* Click on...
=> [Calling][Bugfix] Initial switch to speaker fails, causing the audio device drawer to not populate

AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
* Populate the call screen options with leave call setup 
* Open...
* Click on...
=> [Calling][Bug] Fix the demo app call screen options 

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/CallingViewComponent/Overlay/LobbyOverlayView.swift
* Change the title to be centered for more than one line 
* Open...
* Click on...
=> [Calling][Bug] onhold title should be centered

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Localization/en.lproj/Localizable.strings, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/Cell/ParticipantGridCellViewModel.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/Calling/Grid/ParticipantGridView.swift, AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Utilities/LocalizationKey.swift
Fix the issue where voice over doesn't have announcement when remote participant is on hold
Turn on Voiceover
Open Application using double tap.
Navigate to 'Start Experience' button using swipe gesture and double tap to activate it.
Call setup screen will appear
Now activate 'Join Call' using swipe gesture and double tap to activate it
Meeting will be joined.
Observed the voiceover announcement when other person in meeting is on hold.
=> [Calling][Bugfix] Add accessibility announcement for remote participant onhold and resume

AzureCommunicationUI/AzureCommunicationUIDemoApp/Sources/Views/CallingDemoView.swift
* The audio session in demo app changed the audio selection when joining the call 
* Open...
* Click on...
=> [Calling][Bug] Fix the selected device not correct after join the call 

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/FluentUI/Wrapper/CompositeButton.swift
* Override the button background with primary color 
* Open...
* Click on...
=> [Calling][Bug] Override the backgroud color with primary

AzureCommunicationUI/sdk/AzureCommunicationUICalling/Sources/Presentation/SwiftUI/ViewComponents/Drawer/ExpandableDrawer.swift
* Remove isModel for RTT and Captions drawer 
* Open...
* Click on...
=> [Calling][Bug] Calling screen controls not accessible with Voiceover swipe and keyboard navigation when Caption & RTT is enabled.
